/* FORMATANDO STRINGS */

-- LISTANDO
SELECT DEPARTAMENTO
FROM FUNCIONARIOS;

-- LISTANDO DE FORMA DISTINTA
SELECT DISTINCT DEPARTAMENTO
FROM FUNCIONARIOS;

-- UPPER CASE - LETRAS MAISCULAS
SELECT DISTINCT UPPER(DEPARTAMENTO)
FROM FUNCIONARIOS;

-- LOWER CASE -  LETRAS MINUSCULAS
SELECT DISTINCT LOWER(DEPARTAMENTO)
FROM FUNCIONARIOS;

-- CONCATENANDO STRINGS - COLUNAS
SELECT CARGO || ' - ' || DEPARTAMENTO
FROM FUNCIONARIOS;

-- CONCATENANDO STRING E DEIXANDO COM LETRAS MAISCULAS
SELECT UPPER(CARGO || ' - ' || DEPARTAMENTO) AS "CARGO COMPLETO"
FROM FUNCIONARIOS;

-- REMOVER ESPAÇOS
SELECT '   UNIDADOS   ';

-- CONTANDO CARACTERES
SELECT LENGTH('   UNIDADOS   ');

-- APLICANDO TRIM
SELECT TRIM('   UNIDADOS   ');

-- CRIAR UMA COLUNA AO LADO DA COLUNA CARGO QUE DIGA SE A PESSOA É ASSISTENTE OU NAO
-- 1º OPÇÃO
SELECT NOME, CARGO,
CASE
	WHEN (CARGO LIKE '%Assistant%') = true THEN 'SIM'
	ELSE 'NAO'
END AS "É ASSISTENTE?"
FROM FUNCIONARIOS;

-- 2º OPÇÃO
SELECT NOME, (CARGO LIKE '%Assistant%') AS 'É ASSISTENTE?'
FROM FUNCIONARIOS;