/* FILTROS DE CONTADORES */
SELECT COUNT(*)
FROM FUNCIONARIOS;

-- 1ª OPÇÃO
SELECT SEXO, COUNT(*)
FROM FUNCIONARIOS
WHERE SEXO = 'Masculino'
GROUP BY SEXO;

-- 2ª OPÇÃO
SELECT COUNT(*) AS "QUANTIDADE TOTAL",
(SELECT COUNT(*)
FROM FUNCIONARIOS
WHERE SEXO = 'Masculino'
GROUP BY SEXO) AS "MASCULINO"
FROM FUNCIONARIOS;

-- 3ª OPÇÃO E MELHOR OPÇÃO
SELECT COUNT(*) AS "QUANTIDADE TOTAL",
COUNT(*) FILTER(WHERE SEXO = 'Masculino') AS "MASCULINO",
COUNT(*) FILTER(WHERE SEXO = 'Feminino') AS "FEMININO",
COUNT(*) FILTER(WHERE DEPARTAMENTO = 'Books') AS "Books",
COUNT(*) FILTER(WHERE SALARIO > 140000) AS "Salario > 140k"
FROM FUNCIONARIOS;