/* INTRODUCAO A FILTROS */

-- FILTROS BASEADO EM VALORES NUMERICOS
SELECT NOME, DEPARTAMENTO, SALARIO
FROM FUNCIONARIOS
WHERE SALARIO > 100000;

-- FILTROS BASEADO EM STRINGS
SELECT NOME, DEPARTAMENTO, SALARIO
FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'Ferramentas';

-- FILTROS BASEADOS EM MULTIPLOS TIPOS E COLUNAS - CONSIDERAR OR E AND
SELECT NOME, DEPARTAMENTO, SALARIO
FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'Ferramentas'
	AND SALARIO > 100000;

-- FILTRO BASEADO EM UNICO TIPO E COLUNA - ATENCAO PARA A REGRA DO AND E OR
-- **Em relacionamento 1 x 1 o filtro AND tratando de uma unica coluna, sempre dará falso
SELECT NOME, DEPARTAMENTO, SALARIO
FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'Ferramentas'
	AND DEPARTAMENTO = 'Books';

-- FILTRO BASEADO EM PADRAO DE CARACTERES
SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL
FROM FUNCIONARIOS
WHERE DEPARTAMENTO 
	LIKE 'B%'
GROUP BY DEPARTAMENTO;

-- UTILIZANDO O CARACTER CORINGA NO MEIO DA PALAVRA
SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL
FROM FUNCIONARIOS
WHERE DEPARTAMENTO 
	LIKE 'B%s'
GROUP BY DEPARTAMENTO;

-- E SE EU QUISER FILTRAR O AGRUPAMENTO PELO SALARIO? POR EXEMPLO, MARIO QUE 40.000,00
SELECT DEPARTAMENTO, SUM(SALARIO) AS TOTAL
FROM FUNCIONARIOS
WHERE DEPARTAMENTO 
	LIKE 'B%'
GROUP BY DEPARTAMENTO
HAVING SUM(SALARIO) > 4000000;